version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_feedback
  frontend:
    build:
      context: ./../frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - backend
    ports:
      - '5000:3000'
  backend:
    restart: unless-stopped
    build:
      context: ./../backend
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=5000
      - DB_NAME=db_feedback
      - DB_USER=root
      - DB_HOST=mysql
      - DB_PASSWORD=123456
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - '8000:5000'
    command: ["node","./build/index.js"]

  